library(quantmod)
library(Quandl)
library(rpart)
library(ISLR)
library(tibble)
library(tree)
library(data.table)
library(Metrics)
library(glmnet)
library(caret)
library(magrittr)
library(tidyverse)
library(crypto)
library(crypto2)
library(flexdashboard)
library(plotly)
library(shiny)
library(dplyr)
library(xml2)
library(rvest)
library(tidytext) # tidy implimentation of NLP methods
library(topicmodels) # for LDA topic modelling 
library(tm) # general text mining functions, making document term matrixes
library(SnowballC) # for stemming
library(kableExtra)
library(igraph)
library(networkD3)
library(tree)
library(textdata)
get_sentiments("afinn")
library(ggplot2)
library(leaflet)