---
title: "Blocks"
author: "Yanki Saplan"
date: "`r format(Sys.time(), '%B %d %Y - %H:%M %p')`"
output:
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: scroll
    social: menu
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE)
```

```{r Libraries, include=FALSE}
source('./reqs.R')
source('./scrape.R')
source('./get_data.R')
```

COMMODITIES PREDICTIONS
==============
Row
-----------------
### {.value-box}
```{r Oil Prediction Linear}
valueBox(last_row, caption = "Oil Prediction Linear", icon = "glyphicon-oil")
```

### {.value-box}
```{r Oil RMSE}
valueBox(perf.tree$RMSE,caption = "Oil RMSE", icon = 'glyphicon-sort')
```

{data-height=600}
------------------
### Gold Graph

```{r Gold Graph}
fig <- plot_ly(Gold, type = 'scatter', mode = 'lines')%>%
  add_trace(x = ~Dates, y = ~USD)%>%
  layout(showlegend = F)

fig <- fig %>%
  layout(
         xaxis = list(zerolinecolor = '#ffff',
                      zerolinewidth = 2,
                      gridcolor = 'ffff'),
         yaxis = list(zerolinecolor = '#ffff',
                      zerolinewidth = 2,
                      gridcolor = 'ffff'),
         plot_bgcolor='#e5ecf6', width = 1000)


fig
```

{data-height=600}
------------------
### Oil Graph

```{r Oil Graph}
fig <- plot_ly(Oil, type = 'scatter', mode = 'lines')%>%
  add_trace(x = ~Date, y = ~Value)%>%
  layout(showlegend = F)

fig <- fig %>%
  layout(
         xaxis = list(zerolinecolor = '#ffff',
                      zerolinewidth = 2,
                      gridcolor = 'ffff'),
         yaxis = list(zerolinecolor = '#ffff',
                      zerolinewidth = 2,
                      gridcolor = 'ffff'),
         plot_bgcolor='#e5ecf6', width = 1000)


fig
```


CRYPTO STOCKS
==============
{data-height=600}
------------------
### Crypto Volume

```{r - Volume Graph}
crypto.bar <- plot_ly(
  x = coin_history$name,
  y = coin_history$volume,
  name = "Cryptos",
  type = "bar"
)

crypto.bar
```
{data-height=600}
------------------
### Bitcoin Graph

```{r Bitcoin Graph}
fig <- plot_ly(bitcoin.history, type = 'scatter', mode = 'lines')%>%
  add_trace(x = ~timestamp, y = ~open)%>%
  layout(showlegend = F)

fig <- fig %>%
  layout(
         xaxis = list(zerolinecolor = '#ffff',
                      zerolinewidth = 2,
                      gridcolor = 'ffff'),
         yaxis = list(zerolinecolor = '#ffff',
                      zerolinewidth = 2,
                      gridcolor = 'ffff'),
         plot_bgcolor='#e5ecf6', width = 1000)


fig
```
{data-height=600}
------------------
### Ethereum Graph

```{r Ethereum Graph}
fig <- plot_ly(eth.history, type = 'scatter', mode = 'lines')%>%
  add_trace(x = ~timestamp, y = ~open)%>%
  layout(showlegend = F)

fig <- fig %>%
  layout(
         xaxis = list(zerolinecolor = '#ffff',
                      zerolinewidth = 2,
                      gridcolor = 'ffff'),
         yaxis = list(zerolinecolor = '#ffff',
                      zerolinewidth = 2,
                      gridcolor = 'ffff'),
         plot_bgcolor='#e5ecf6', width = 1000)


fig
```
{data-height=600}
------------------
### Cardano Graph

```{r Cardano Graph}
fig <- plot_ly(ada.history, type = 'scatter', mode = 'lines')%>%
  add_trace(x = ~timestamp, y = ~open)%>%
  layout(showlegend = F)

fig <- fig %>%
  layout(
         xaxis = list(zerolinecolor = '#ffff',
                      zerolinewidth = 2,
                      gridcolor = 'ffff'),
         yaxis = list(zerolinecolor = '#ffff',
                      zerolinewidth = 2,
                      gridcolor = 'ffff'),
         plot_bgcolor='#e5ecf6', width = 1000)


fig
```
{data-height=600}
------------------
### Solana Graph

```{r Solana Graph}
fig <- plot_ly(sol.history, type = 'scatter', mode = 'lines')%>%
  add_trace(x = ~timestamp, y = ~open)%>%
  layout(showlegend = F)

fig <- fig %>%
  layout(
         xaxis = list(zerolinecolor = '#ffff',
                      zerolinewidth = 2,
                      gridcolor = 'ffff'),
         yaxis = list(zerolinecolor = '#ffff',
                      zerolinewidth = 2,
                      gridcolor = 'ffff'),
         plot_bgcolor='#e5ecf6', width = 1000)


fig
```

CRYPTO IN-DEPTH
==============
Row
------------------------------------
###Bitcoin
```{r Bitcoin Gauge}
fig <- plot_ly(
    domain = bitcoin.history.max.gauge$timestamp,
    value = bitcoin.history.max.gauge$high,
    title = bitcoin.history.max.gauge$timestamp,
    type = "indicator",
    mode = "gauge+number")

fig
```

###Ethereuem
```{r Eth Gauge}
fig <- plot_ly(
    domain = eth.history.max.gauge$timestamp,
    value = eth.history.max.gauge$high,
    title = eth.history.max.gauge$timestamp,
    type = "indicator",
    mode = "gauge+number")

fig
```

###Cardano
```{r Ada Gauge}
fig <- plot_ly(
    domain = ada.history.max.gauge$timestamp,
    value = ada.history.max.gauge$high,
    title = ada.history.max.gauge$timestamp,
    type = "indicator",
    mode = "gauge+number")

fig
```

###Solana
```{r Sol Gauge}
fig <- plot_ly(
    domain = sol.history.max.gauge$timestamp,
    value = sol.history.max.gauge$high,
    title = sol.history.max.gauge$timestamp,
    type = "indicator",
    mode = "gauge+number")

fig
```

Row
------------------------------------
### CRYPTO RELATIONS
```{r Crypto Relations}
# create a dataset:
data.crypto <- data_frame(
  from=crypto_df$id_review,
  to=crypto_df$word
)

# Plot
p <- simpleNetwork(data.crypto, height="2000px", width="2000px")
p
```

Row
------------------------------------
### REVIEWS
```{r Crypto Reviews}
term_frequency_review.crypto %>% 
  arrange(desc(tf)) %>% 
  mutate(word = factor(word, levels = rev(unique(word)))) %>% 
  group_by(document) %>% 
  top_n(15, tf) %>% 
  ungroup() %>% 
  ggplot(aes(word, tf, fill = document)) + 
  geom_col(show.legend = FALSE) + 
  labs(x = NULL, y = "tf-idf") + 
  facet_wrap(~document, ncol = 2, scales = "free") + 
  coord_flip()
```

### News Scores Daily
```{r Crypto Source Scores, echo=FALSE}
Sentiment_Analysis.crypto
```


RELATIONS
==============
Row
------------------------------------
```{r Relations}
# create a dataset:
data <- data_frame(
  from=text_df$id_review,
  to=text_df$word
)

# Plot
p <- simpleNetwork(data, height="2000px", width="2000px")
p
```

Row
------------------------------------

### Terms
```{r Web Scraped Data MCW}
top_terms_by_topic_LDA(reviews$text, number_of_topics = 4)
```
Row
------------------------------------
### Cleaned Data
```{r Cleaned MCW}
top_terms_by_topic_LDA(cleaned_documents$terms, number_of_topics = 4)
```
Row
------------------------------------
### Informative
```{r More Informative}
# stem the words (e.g. convert each word to its stem, where applicable)
reviewsDTM_tidy_cleaned <- reviewsDTM_tidy_cleaned %>% 
    mutate(stem = wordStem(term))

# reconstruct our documents
cleaned_documents <- reviewsDTM_tidy_cleaned %>%
    group_by(document) %>% 
    mutate(terms = toString(rep(stem, count))) %>%
    select(document, terms) %>%
    unique()

# now let's look at the new most informative terms
top_terms_by_topic_LDA(cleaned_documents$terms, number_of_topics = 3)
```

### Word Polarity
```{r Word Polarity}
Sentiment_Analysis_Word_Count %>% 
  group_by(sentiment) %>% 
  top_n(12, n) %>%
  ungroup() %>%
  mutate(word = reorder(word, n)) %>%
  ggplot(aes(word, n, fill = sentiment)) + 
  geom_col(show.legend = FALSE) + 
  facet_wrap(~sentiment, scales = "free_y") + 
  labs(y = "Contribution to Sentiment", x = NULL) + 
  coord_flip()
```

### Source Scores
```{r Source Scores}
Sentiment_Analysis <- text_df %>% 
  inner_join(get_sentiments("bing"), "word") %>% 
  count(id_review, sentiment) %>% 
  spread(sentiment, n, fill = 0) %>% 
  mutate(sentiment = positive - negative)

Sentiment_Analysis
```

### Frequency Tables
```{r Frequency}
term_frequency_review %>% 
  arrange(desc(tf)) %>% 
  mutate(word = factor(word, levels = rev(unique(word)))) %>% 
  group_by(document) %>% 
  top_n(15, tf) %>% 
  ungroup() %>% 
  ggplot(aes(word, tf, fill = document)) + 
  geom_col(show.legend = FALSE) + 
  labs(x = NULL, y = "tf-idf") + 
  facet_wrap(~document, ncol = 2, scales = "free") + 
  coord_flip()
```








